language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
notifications:
  irc:
    channels:
      - "irc.freenode.org#berkshelf"
    skip_join: true
    use_notice: true
env: USE_SYSTEM_GECODE=1
bundler_args: --without development --jobs 7
before_install:
  - sudo apt-get install -qq libarchive12 libarchive-dev libgecode-dev
before_script:
  - git config --global user.email "ci@berkshelf.com"
  - git config --global user.name "Berkshelf"
script: bundle exec rspec --color --format progress
